In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
list1 = [10, 20, 30, 40, 50, 60]
list1

[10, 20, 30, 40, 50, 60]

In [3]:
type(list1)

list

In [4]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [5]:
arr1.data

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.dtype

dtype('int32')

In [8]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [12]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [13]:
arr3.nbytes

40

In [14]:
len(arr3)

10

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [18]:
a = np.array([10, 20, 30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [19]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [20]:
ar1 = np.arange(1, 20)
ar1[ar1 %2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
ar1 = np.arange(1, 20)
ar1[ar1 %2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [23]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [24]:
#Rastgele sayı üretimi

In [25]:
np.random.random(4)

array([0.14672033, 0.45617945, 0.11413035, 0.99518705])

In [26]:
np.random.randint(0, 500, 5)

array([465, 322, 410, 328, 271])

In [27]:
np.random.randint(0, 500, 10)

array([313, 358, 484, 192, 225, 151, 279,  91, 330, 425])

In [28]:
#seed (çekirdek)

In [29]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [30]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [31]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [32]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [33]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [34]:
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [35]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [37]:
b2 = np.random.randn(10)
b2

array([-1.70608593, -1.15911942, -0.13484072,  0.39052784,  0.16690464,
        0.18450186,  0.80770591,  0.07295968,  0.63878701,  0.3296463 ])

In [38]:
arr1

array([10, 20, 30, 40, 50, 60])

In [39]:
#enumaration

In [40]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [41]:
#dizi üzerindeki operasyonlar

In [42]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [43]:
arr2.sum()

190

In [44]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [45]:
#min(), max(), argmin(), argmax(), mean(), median(), var()

In [46]:
np.std(arr2)

5.477225575051661

In [47]:
#2D Dizi

In [49]:
A = np.array([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [50]:
#sum(), max(), min(), mean(), median(), var(), std()

In [51]:
#sütun bazlı minimum
np.amin(A, axis = 0)

array([1, 2, 1, 0])

In [52]:
#satır bazı minimum
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [53]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [54]:
#Eleman değiştirme / dönüştürme

In [55]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [56]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [57]:
ar2 = np.array([10, 20, 30, 10, 10, 20, 20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [58]:
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [59]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
np.put(p2, [0, 3, 5], [33, 55, 99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [61]:
#Eksik değerler ile ilgilenme

In [62]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [63]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [64]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [65]:
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [66]:
np.isnan(a).any()

False

In [67]:
A = np.array([[1,2,np.nan, 4], [np.nan, 6, 7, 8], [10, np.nan, 12, 13], [14, 15, 16, 17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [69]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [70]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [ ]:
#dizileri dikey ve yatay olarak birleştirmek (horizontal-vertical)