In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
A = np.array([[1,2,3,4], [5,6,7,8], [10,11,12,13], [14,15,16,17]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [3]:
A.dtype

dtype('int32')

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.random.randint(0, 500, (10,10))

array([[299, 149, 158,  39, 392, 454,  83, 211,  94, 158],
       [ 28,  82, 169, 391, 435, 379, 133, 241, 437,  65],
       [ 59, 154,  60, 483, 101,  84,  28, 155, 222,  14],
       [357, 262,  41, 394, 167, 368, 387, 138,  98,  89],
       [363,  73, 301, 378, 336, 152, 241, 277, 370, 184],
       [159, 337, 402, 180, 485, 356, 440,  22,  60, 350],
       [301, 447,  61, 386, 311, 199, 153, 398, 467, 233],
       [385, 399,  20, 218, 376,   2, 193, 307, 397, 302],
       [384, 385, 470, 188, 152, 419,  18,  29, 115, 226],
       [354,  73, 132,  24, 291, 380, 219, 364, 184,  34]])

In [10]:
mat1 = np.random.randint(0, 1000, 100).reshape(10, 10)
mat1

array([[351, 436, 399, 123, 204, 609, 621, 912, 572, 155],
       [199, 134, 961, 858, 411, 513,  52, 759,  64, 727],
       [916, 461, 835, 715, 504, 947,  19, 455, 375, 393],
       [972, 971, 267, 327, 410, 165, 906, 501, 426, 121],
       [695, 266, 254, 173, 506, 728, 471, 605, 556, 137],
       [994, 755, 496, 740,  10,  20, 775,  41, 346, 872],
       [965, 181, 904, 691, 270, 751, 816, 953, 198, 990],
       [219, 226, 516, 375, 913, 926,   3, 135, 443, 212],
       [307, 201, 550, 326, 588, 578, 414,  39, 907,  57],
       [835, 855, 883, 914, 761, 341, 407, 637, 206, 246]])

In [11]:
mat1[0, 0]

351

In [15]:
mat1[mat1 > 990]

array([994])

In [16]:
#Identity (Birim) Matrix

In [17]:
I = np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
D = np.diag([1,2,3,4,5,6,7,8])
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [19]:
#Triangular Matrix

In [23]:
M = np.random.randn(5, 5)
U = np.triu(M)
L = np.tril(M)

print("our matrix - \n", M)
print("\n")

print("upper triangular matrix - \n", U)
print("\n")

print("lower triangular matrix - \n", L)

our matrix - 
 [[ 0.7448032   0.17540969  1.29977674 -1.67762801 -0.55496773]
 [-0.63877955  1.44086397 -0.93572826  0.43361251 -2.09594619]
 [-0.50041928  0.394563    1.37959548 -0.8131861   3.14485789]
 [-0.43413431 -0.62360392  0.47089691 -1.52602489 -1.2538058 ]
 [ 1.90898721 -0.7006358   0.60609805 -0.16876979 -2.03755378]]


upper triangular matrix - 
 [[ 0.7448032   0.17540969  1.29977674 -1.67762801 -0.55496773]
 [ 0.          1.44086397 -0.93572826  0.43361251 -2.09594619]
 [ 0.          0.          1.37959548 -0.8131861   3.14485789]
 [ 0.          0.          0.         -1.52602489 -1.2538058 ]
 [ 0.          0.          0.          0.         -2.03755378]]


lower triangular matrix - 
 [[ 0.7448032   0.          0.          0.          0.        ]
 [-0.63877955  1.44086397  0.          0.          0.        ]
 [-0.50041928  0.394563    1.37959548  0.          0.        ]
 [-0.43413431 -0.62360392  0.47089691 -1.52602489  0.        ]
 [ 1.90898721 -0.7006358   0.60609805 -0.

In [25]:
np.random.uniform(10, 20, size = (5,5))

array([[12.22297473, 19.03521113, 10.88125505, 12.08371679, 19.75847723],
       [15.88845959, 14.36464168, 17.41544277, 18.66942349, 10.18237528],
       [10.43289867, 11.39771065, 18.36319181, 16.89432495, 18.82745223],
       [17.31213437, 10.06004401, 13.29079269, 19.20554424, 17.30592719],
       [19.46747448, 18.01255782, 15.06095261, 12.91012516, 10.42323649]])

In [24]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [26]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17])

In [27]:
A.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17])

In [28]:
#Matrisin satır/sütunlarını SWAP (değiştirme) işlemi

In [29]:
#satır SWAP
m1 = np.arange(0, 16).reshape(4, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
m1[[3,2]] = m1[[2,3]]
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [31]:
#sütun SWAP
m2 = np.arange(0, 36).reshape(6,6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
m2[:, [2,3]] = m2[:, [3,2]]
m2

array([[ 0,  1,  3,  2,  4,  5],
       [ 6,  7,  9,  8, 10, 11],
       [12, 13, 15, 14, 16, 17],
       [18, 19, 21, 20, 22, 23],
       [24, 25, 27, 26, 28, 29],
       [30, 31, 33, 32, 34, 35]])

In [33]:
#TRANSPOZE
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])

print("\n Matrix (M) ==> \n", M)

print("\nTranspose of M ==> \n", np.transpose(M))

#OR

print("\nTranspose of M ==> \n", M.T)


 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Transpose of M ==> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]

Transpose of M ==> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [35]:
#Determinant
print("Determinant of M ==> ", np.linalg.det(M))

Determinant of M ==>  195.0


In [37]:
#Inverse (Ters)
print("Inverse of M ==> \n", np.linalg.inv(M))

Inverse of M ==> 
 [[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


In [38]:
#Matrix Power (Kuvvet)

In [39]:
M1 = np.array([[1,2], [4,5]])
M1

array([[1, 2],
       [4, 5]])

In [40]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [41]:
np.linalg.matrix_power(M1, 3)

array([[ 57,  78],
       [156, 213]])

In [42]:
#Tensor

In [43]:
T1 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,20,30], [40,50,60], [70,80,90]],
    [[100, 200, 300], [400, 500, 600], [700, 800, 900]],
])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [44]:
T2 = np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]]
])
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [45]:
#Toplama
A = T1 + T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [46]:
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [47]:
#çıkarma
S = T1 - T2
S

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [48]:
np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [49]:
#çarpma
P = T1 * T2
P

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [50]:
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [51]:
#bölme
D = T1 / T2
D

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [52]:
np.divide(T1, T2)

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [53]:
#Denklem Çözme

In [54]:
#AX = B

In [55]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
B = np.random.random((3,1))
B

array([[0.24734832],
       [0.57880744],
       [0.09522041]])

In [57]:
X = np.dot(np.linalg.inv(A), B)
X

array([[-2.56944908e+15],
       [ 5.13889817e+15],
       [-2.56944908e+15]])

In [58]:
X = np.matmul(np.linalg.inv(A), B)
X

array([[-2.56944908e+15],
       [ 5.13889817e+15],
       [-2.56944908e+15]])

In [59]:
X = np.linalg.inv(A)@B
X

array([[-2.56944908e+15],
       [ 5.13889817e+15],
       [-2.56944908e+15]])

In [60]:
X = np.linalg.solve(A, B)
X

array([[-2.56944908e+15],
       [ 5.13889817e+15],
       [-2.56944908e+15]])

In [61]:
#SCIPY

In [62]:
#scipy.linalg, scipy.special, scipy.integrate, scipy.optimize, scipy.fftpack, scipy.signal,
#scipy.stats, scipy.ndimage, scipy.io, scipy.spatial

In [64]:
from scipy import linalg

In [65]:
#inverse
A = np.array([[1,2], [3,4]])
print(A)
B = linalg.inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [66]:
#transpose
b = np.array([[5,6]])
print(b)
print(b.T)

[[5 6]]
[[5]
 [6]]


In [67]:
#denklem takımı çözümü

In [68]:
A = np.array([[1,3,5], [2,5,1], [2,3,8]])
print(A)
b = np.array([[10], [8], [3]])
print(b)
print("linalg.inv(A).dot(b) Matrix Inverse ile Denklem Takımı Çözümü")
print(linalg.inv(A).dot(b)) #slow (yavaş çözüm)
print("np.linalg.solve(A, b) ile Denklem Takımı Çözümü")
print(np.linalg.solve(A, b)) #fast (hızlı çözüm)

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]
linalg.inv(A).dot(b) Matrix Inverse ile Denklem Takımı Çözümü
[[-9.28]
 [ 5.16]
 [ 0.76]]
np.linalg.solve(A, b) ile Denklem Takımı Çözümü
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [69]:
#integral
from scipy import integrate
x2 = lambda x : x**2
I = integrate.quad(x2, 0, 6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [70]:
#türev
from scipy.misc import derivative
def f(x):
    return x**3 + x**2
D = derivative(f, 1.0, dx = 1e-6)
print(D)

4.999999999921734
