In [1]:
#PANDAS
import numpy as np
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Seriler

In [4]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [5]:
s1.dtype

dtype('int32')

In [6]:
s1.nbytes

28

In [7]:
len(s1)

7

In [8]:
s1.count()

7

In [9]:
#Python List -> Series
s0 = pd.Series([1,2,3], index = ['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [10]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [11]:
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.63006681, 0.05938317, 0.08478801, 0.54785623, 0.30702959,
        0.79165008, 0.14847016, 0.91219152, 0.93283615, 0.43554097]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.630067
 1    0.059383
 2    0.084788
 3    0.547856
 4    0.307030
 5    0.791650
 6    0.148470
 7    0.912192
 8    0.932836
 9    0.435541
 dtype: float64)

In [12]:
#Dictionary (Sözlük) -> Series
dict1 = {'a1' : 10, 'a2' : 20, 'a3' : 30, 'a4' : 40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [13]:
pd.Series(99, index = [0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [14]:
s

0    0.630067
1    0.059383
2    0.084788
3    0.547856
4    0.307030
5    0.791650
6    0.148470
7    0.912192
8    0.932836
9    0.435541
dtype: float64

In [15]:
s[:]

0    0.630067
1    0.059383
2    0.084788
3    0.547856
4    0.307030
5    0.791650
6    0.148470
7    0.912192
8    0.932836
9    0.435541
dtype: float64

In [16]:
s[0:3]

0    0.630067
1    0.059383
2    0.084788
dtype: float64

In [18]:
s[-1:]

9    0.435541
dtype: float64

In [19]:
s[:-1]

0    0.630067
1    0.059383
2    0.084788
3    0.547856
4    0.307030
5    0.791650
6    0.148470
7    0.912192
8    0.932836
dtype: float64

In [21]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [22]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [23]:
s4 = s2.append(s3)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [24]:
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [25]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [26]:
s4.drop('a4', inplace = True)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [27]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [28]:
s4 = s4.append(pd.Series({'a4' : 7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [29]:
#Seriler üzerindeki operasyonlar

In [30]:
v1 = np.array([10, 20, 30])
v2 = np.array([1, 2, 3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1, s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [31]:
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [32]:
s1.sub(s2)

0     9
1    18
2    27
dtype: int32

In [33]:
s1.subtract(s2)

0     9
1    18
2    27
dtype: int32

In [34]:
s1.add(9)

0    19
1    29
2    39
dtype: int32

In [35]:
s1.multiply(s2)

0    10
1    40
2    90
dtype: int32

In [36]:
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int32

In [37]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [38]:
#max(), min(), mean(), median(), std()

In [39]:
s1.equals(s2)

False

In [40]:
s5 = pd.Series([1,1,2,2,3,3], index = [0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [41]:
s5.value_counts()

1    2
2    2
3    2
dtype: int64

In [42]:
#Veri Çerçeveleri (DataFrames)

In [43]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [44]:
lang = ['Java', 'Python', 'C', 'C++']
df = pd.DataFrame(lang)
df

0
0    Java
1  Python
2       C
3     C++

In [45]:
rating = [1, 2, 3, 4]
df[1] = rating #indeks değil sütun adı!!!
df

0  1
0    Java  1
1  Python  2
2       C  3
3     C++  4

In [46]:
df.columns = ['Language', 'Rating']

In [47]:
df

Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [48]:
#Dictionary -> DataFrame

In [49]:
data = [{'a' : 1, 'b' : 2}, {'a' : 5, 'b' : 10, 'c' : 20}]

df2 = pd.DataFrame(data)
df3 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b'])
df4 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c'])
df5 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c', 'd'])

In [50]:
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [51]:
df3

a   b
row1  1   2
row2  5  10

In [52]:
df4

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [53]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [54]:
df0 = pd.DataFrame({'ID' : [1,2,3,4], 'Name' : ['Doğu', 'Batı', 'Kuzey', 'Güney']})
df0

ID   Name
0   1   Doğu
1   2   Batı
2   3  Kuzey
3   4  Güney

In [55]:
#Seri kullanarak DF yaratma
mydict = {'A' : pd.Series([1,2,3], index = ['a', 'b', 'c']),
         'B' : pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}

df1 = pd.DataFrame(mydict)
df1

A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

In [56]:
dates = pd.date_range(start = '2023-11-12', end = '2023-11-18')
dates

DatetimeIndex(['2023-11-12', '2023-11-13', '2023-11-14', '2023-11-15',
               '2023-11-16', '2023-11-17', '2023-11-18'],
              dtype='datetime64[ns]', freq='D')

In [57]:
dates = pd.date_range('today', periods = 7)
dates

DatetimeIndex(['2023-11-18 22:02:16.745847', '2023-11-19 22:02:16.745847',
               '2023-11-20 22:02:16.745847', '2023-11-21 22:02:16.745847',
               '2023-11-22 22:02:16.745847', '2023-11-23 22:02:16.745847',
               '2023-11-24 22:02:16.745847'],
              dtype='datetime64[ns]', freq='D')

In [58]:
dates = pd.date_range(start = '2023-11-12', periods = 7)
dates

DatetimeIndex(['2023-11-12', '2023-11-13', '2023-11-14', '2023-11-15',
               '2023-11-16', '2023-11-17', '2023-11-18'],
              dtype='datetime64[ns]', freq='D')

In [59]:
M = np.random.random((7,7))
M

array([[0.25097273, 0.96611119, 0.8209422 , 0.06189588, 0.54859908,
        0.20027066, 0.07110071],
       [0.79746739, 0.32982289, 0.06268501, 0.38208845, 0.13331062,
        0.3675159 , 0.7912587 ],
       [0.86340366, 0.45999918, 0.9174941 , 0.88277768, 0.16677763,
        0.63478107, 0.96363786],
       [0.63473174, 0.14578947, 0.79960634, 0.03518167, 0.71417795,
        0.62755198, 0.94875392],
       [0.78367249, 0.26856548, 0.33890094, 0.94186231, 0.93674411,
        0.47513752, 0.96809173],
       [0.64169056, 0.53660822, 0.52425001, 0.832499  , 0.37037367,
        0.31949906, 0.65847181],
       [0.99569505, 0.07584337, 0.04333586, 0.73583088, 0.33689592,
        0.17805426, 0.49188856]])

In [60]:
dframe = pd.DataFrame(M, index = dates)
dframe

0         1         2         3         4         5  \
2023-11-12  0.250973  0.966111  0.820942  0.061896  0.548599  0.200271   
2023-11-13  0.797467  0.329823  0.062685  0.382088  0.133311  0.367516   
2023-11-14  0.863404  0.459999  0.917494  0.882778  0.166778  0.634781   
2023-11-15  0.634732  0.145789  0.799606  0.035182  0.714178  0.627552   
2023-11-16  0.783672  0.268565  0.338901  0.941862  0.936744  0.475138   
2023-11-17  0.641691  0.536608  0.524250  0.832499  0.370374  0.319499   
2023-11-18  0.995695  0.075843  0.043336  0.735831  0.336896  0.178054   

                   6  
2023-11-12  0.071101  
2023-11-13  0.791259  
2023-11-14  0.963638  
2023-11-15  0.948754  
2023-11-16  0.968092  
2023-11-17  0.658472  
2023-11-18  0.491889

In [61]:
dframe.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

C1        C2        C3        C4        C5        C6  \
2023-11-12  0.250973  0.966111  0.820942  0.061896  0.548599  0.200271   
2023-11-13  0.797467  0.329823  0.062685  0.382088  0.133311  0.367516   
2023-11-14  0.863404  0.459999  0.917494  0.882778  0.166778  0.634781   
2023-11-15  0.634732  0.145789  0.799606  0.035182  0.714178  0.627552   
2023-11-16  0.783672  0.268565  0.338901  0.941862  0.936744  0.475138   
2023-11-17  0.641691  0.536608  0.524250  0.832499  0.370374  0.319499   
2023-11-18  0.995695  0.075843  0.043336  0.735831  0.336896  0.178054   

                  C7  
2023-11-12  0.071101  
2023-11-13  0.791259  
2023-11-14  0.963638  
2023-11-15  0.948754  
2023-11-16  0.968092  
2023-11-17  0.658472  
2023-11-18  0.491889

In [62]:
dframe.index

DatetimeIndex(['2023-11-12', '2023-11-13', '2023-11-14', '2023-11-15',
               '2023-11-16', '2023-11-17', '2023-11-18'],
              dtype='datetime64[ns]', freq='D')

In [63]:
dframe.columns

Index(['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7'], dtype='object')

In [64]:
dframe.dtypes

C1    float64
C2    float64
C3    float64
C4    float64
C5    float64
C6    float64
C7    float64
dtype: object

In [65]:
dframe.sort_values(by = 'C1') #ascending (küçükten büyüğe)

C1        C2        C3        C4        C5        C6  \
2023-11-12  0.250973  0.966111  0.820942  0.061896  0.548599  0.200271   
2023-11-15  0.634732  0.145789  0.799606  0.035182  0.714178  0.627552   
2023-11-17  0.641691  0.536608  0.524250  0.832499  0.370374  0.319499   
2023-11-16  0.783672  0.268565  0.338901  0.941862  0.936744  0.475138   
2023-11-13  0.797467  0.329823  0.062685  0.382088  0.133311  0.367516   
2023-11-14  0.863404  0.459999  0.917494  0.882778  0.166778  0.634781   
2023-11-18  0.995695  0.075843  0.043336  0.735831  0.336896  0.178054   

                  C7  
2023-11-12  0.071101  
2023-11-15  0.948754  
2023-11-17  0.658472  
2023-11-16  0.968092  
2023-11-13  0.791259  
2023-11-14  0.963638  
2023-11-18  0.491889

In [66]:
dframe.sort_values(by = 'C1', ascending = False) #descending

C1        C2        C3        C4        C5        C6  \
2023-11-18  0.995695  0.075843  0.043336  0.735831  0.336896  0.178054   
2023-11-14  0.863404  0.459999  0.917494  0.882778  0.166778  0.634781   
2023-11-13  0.797467  0.329823  0.062685  0.382088  0.133311  0.367516   
2023-11-16  0.783672  0.268565  0.338901  0.941862  0.936744  0.475138   
2023-11-17  0.641691  0.536608  0.524250  0.832499  0.370374  0.319499   
2023-11-15  0.634732  0.145789  0.799606  0.035182  0.714178  0.627552   
2023-11-12  0.250973  0.966111  0.820942  0.061896  0.548599  0.200271   

                  C7  
2023-11-18  0.491889  
2023-11-14  0.963638  
2023-11-13  0.791259  
2023-11-16  0.968092  
2023-11-17  0.658472  
2023-11-15  0.948754  
2023-11-12  0.071101

In [ ]:
#Silme İşlemleri